name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  # Using github sha for unique tagging
  BUILD_TAG: ${{ github.sha }}
  DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
  # Image names
  BACKEND_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/weather-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/weather-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build Backend Image (Used by backend, worker, historical_worker)
      - name: Build and push Backend
        run: |
          docker build -t $BACKEND_IMAGE:$BUILD_TAG -t $BACKEND_IMAGE:latest ./backend
          docker push $BACKEND_IMAGE:$BUILD_TAG
          docker push $BACKEND_IMAGE:latest

      # Build Frontend Image
      - name: Build and push Frontend
        run: |
          docker build -t $FRONTEND_IMAGE:$BUILD_TAG -t $FRONTEND_IMAGE:latest ./frontend
          docker push $FRONTEND_IMAGE:$BUILD_TAG
          docker push $FRONTEND_IMAGE:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Install Ansible requirements
        run: ansible-galaxy collection install community.docker

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          # Inventory vars
          SERVER_ADDRESS: "${{ secrets.SERVER_ADDRESS }}"
          SERVER_USER: "${{ secrets.SERVER_USER }}"
          SERVER_PORT: "${{ secrets.SERVER_PORT }}"
          
          # Playbook vars
          DOCKER_HUB_USERNAME: "${{ secrets.DOCKER_HUB_USERNAME }}"
          DOCKER_HUB_TOKEN: "${{ secrets.DOCKER_HUB_TOKEN }}"
          POSTGRES_USER: "${{ secrets.POSTGRES_USER }}"
          POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD }}"
          POSTGRES_DB: "${{ secrets.POSTGRES_DB }}"
          WEATHER_API_KEY: "${{ secrets.WEATHER_API_KEY }}"
        run: ansible-playbook -i ansible/inventory.yaml ansible/deploy.yaml
